### ISSUE TITLE
Module does not install

### ISSUE THREAD

**Issue by jonahadmin** [StackStorm-Exchange/stackstorm-aws#52]
```
# st2 pack search aws
+----------+--------------------------------------+---------+------------------+
| name     | description                          | version | author           |
+----------+--------------------------------------+---------+------------------+
| aws      | st2 content pack containing Amazon   | 1.0.0   | StackStorm, Inc. |
|          | Web Services integrations.           |         |                  |
| libcloud | st2 content pack containing libcloud | 0.4.0   | StackStorm, Inc. |
|          | integrations                         |         |                  |
+----------+--------------------------------------+---------+------------------+
[root@it-ops01 st2]# st2 pack install aws

	[ succeeded ] download pack
	[ succeeded ] make a prerun
	[ succeeded ] install pack dependencies
	[  failed   ] register pack

id: 5995adb15b0c7d7a3f64cb15
action.ref: packs.install
parameters:
  packs:
  - aws
status: failed
result_task: register pack
result:
  exit_code: 1
  result: None
  stderr: "st2.actions.python.St2RegisterAction: DEBUG    Calling client method \"register\" with kwargs \"{'types': [u'all'], 'packs': [u'aws']}\"\n/opt/stackstorm/st2/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py\", line 259, in <module>\n    obj.run()\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py\", line 155, in run\n    output = action.run(**self._parameters)\n  File \"/opt/stackstorm/packs/packs/actions/pack_mgmt/register.py\", line 81, in run\n    format_func=format_result)\n  File \"/opt/stackstorm/packs/packs/actions/pack_mgmt/register.py\", line 149, in _run_client_method\n    result = method(**method_kwargs)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py\", line 39, in decorate\n    return func(*args, **kwargs)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py\", line 456, in register\n    self.handle_error(response)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py\", line 165, in handle_error\n    response.raise_for_status()\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/requests/models.py\", line 928, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 504 Server Error: Gateway Time-out\nUnable to retrieve detailed message from the HTTP response. Expecting value: line 1 column 1 (char 0)\n for url: https://ourserver.example.com/api/v1/packs/register\n"
  stdout: ''
error: st2.actions.python.St2RegisterAction: DEBUG    Calling client method "register" with kwargs "{'types': [u'all'], 'packs': [u'aws']}"
/opt/stackstorm/st2/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 259, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 155, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/register.py", line 81, in run
    format_func=format_result)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/register.py", line 149, in _run_client_method
    result = method(**method_kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 39, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 456, in register
    self.handle_error(response)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 165, in handle_error
    response.raise_for_status()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out
Unable to retrieve detailed message from the HTTP response. Expecting value: line 1 column 1 (char 0)
 for url: https://ourserver.example.com/api/v1/packs/register

traceback: None
failed_on: register pack
start_timestamp: 2017-08-17T14:52:33.769168Z
end_timestamp: 2017-08-17T14:54:37.478140Z
+--------------------------+-------------------------+--------------------------+-------------------------+--------------------------+
| id                       | status                  | task                     | action                  | start_timestamp          |
+--------------------------+-------------------------+--------------------------+-------------------------+--------------------------+
| 5995adb25b0c7d795c7e1f5c | succeeded (6s elapsed)  | download pack            | packs.download          | Thu, 17 Aug 2017         |
|                          |                         |                          |                         | 14:52:34 UTC             |
| 5995adb85b0c7d795c7e1f5e | succeeded (3s elapsed)  | make a prerun            | packs.virtualenv_prerun | Thu, 17 Aug 2017         |
|                          |                         |                          |                         | 14:52:40 UTC             |
| 5995adbc5b0c7d795c7e1f60 | succeeded (20s elapsed) | install pack             | packs.setup_virtualenv  | Thu, 17 Aug 2017         |
|                          |                         | dependencies             |                         | 14:52:44 UTC             |
| 5995add05b0c7d795c7e1f62 | failed (93s elapsed)    | register pack            | packs.load              | Thu, 17 Aug 2017         |
|                          |                         |                          |                         | 14:53:04 UTC             |
+--------------------------+-------------------------+--------------------------+-------------------------+--------------------------+```

**Comment by jonahadmin** [comment]
I tried increasing the proxy timeouts in the nginx st2.conf to 120 seconds, which caused it to fail after 123 seconds elapsed rather than 93.

I then increased it to 240 seconds, and the output is now:
```
# st2 pack install aws

	[ succeeded ] download pack
	[ succeeded ] make a prerun
	[ succeeded ] install pack dependencies
	[  timeout  ] register pack

+-------------+--------------------------------------------------------------+
| Property    | Value                                                        |
+-------------+--------------------------------------------------------------+
| name        | aws                                                          |
| description | st2 content pack containing Amazon Web Services              |
|             | integrations.                                                |
| version     | 1.0.0                                                        |
| author      | StackStorm, Inc.                                             |
+-------------+--------------------------------------------------------------+
```

**Comment by LindsayHill** [comment]
As a short-term measure, we've increased the pack install timeout here: https://github.com/StackStorm/st2/pull/3685

We also have an issue open against the st2 repo to optimize this step https://github.com/StackStorm/st2/issues/3686
