### ISSUE TITLE
aws.AWSSQSSensor not able to connect to queue.amazonaws.com

### ISSUE THREAD

**Issue by um255** [StackStorm-Exchange/stackstorm-aws#56]
Hi Team,

I have configured the aws config file as below
```yaml
region: "us-east-1"
aws_access_key_id: "actualkey"
aws_secret_access_key: "acutalsecretkey"
st2_user_data: ""
sqs_sensor:
  input_queues:
    - "TestQueue"
sqs_other:
  max_number_of_messages: 10
```
I have also configured the virtual environment for aws pack under `/opt/stackstorm/virtualenvs/aws`

The sensor is also registered
```sh
/opt/stackstorm/virtualenvs/aws/lib/python2.7/site-packages/botocore# st2 sensor list
+-------------------------------------------+----------------+-----------------------------------------------------+---------+
| ref                                       | pack           | description                                         | enabled |
+-------------------------------------------+----------------+-----------------------------------------------------+---------+
| linux.FileWatchSensor                     | linux          | Sensor which monitors files for new lines           | True    |
| stackstorm-aws.ServiceNotificationsSensor | stackstorm-aws | Sensor which exposes an HTTP interface and listens  | True    |
|                                           |                | for AWS service notifications delivered via AWS SNS |         |
| stackstorm-aws.AWSSQSSensor               | stackstorm-aws | Sensor which monitors a SQS queue for new messages  | True    |
| aws.ServiceNotificationsSensor            | aws            | Sensor which exposes an HTTP interface and listens  | True    |
|                                           |                | for AWS service notifications delivered via AWS SNS |         |
| aws.AWSSQSSensor                          | aws            | Sensor which monitors a SQS queue for new messages  | True    |
+-------------------------------------------+----------------+-----------------------------------------------------+---------+
```

But when I try to debug the sensor using below command it throws error

```sh
/opt/stackstorm/st2/bin/st2sensorcontainer --config-file=/etc/st2/st2.conf --debug --sensor-ref=aws.AWSSQSSensor

2017-08-23 20:31:03,893 DEBUG [-] Setting sqs timeout as (60, 60)
2017-08-23 20:31:03,893 DEBUG [-] Loading sqs:sqs
2017-08-23 20:31:03,894 INFO [-] Calling sqs:get_queue_url with {'QueueName': u'TestQueue'}
2017-08-23 20:31:03,894 DEBUG [-] Event before-parameter-build.sqs.GetQueueUrl: calling handler <function generate_idempotent_uuid at 0x7f849bd83938>
2017-08-23 20:31:03,895 DEBUG [-] Making request for OperationModel(name=GetQueueUrl) (verify_ssl=True) with params: {'body': {'Action': u'GetQueueUrl', 'Version': u'2012-11-05', 'QueueName': u'TestQueue'}, 'url': u'https://queue.amazonaws.com/', 'headers': {'User-Agent': 'Boto3/1.3.1 Python/2.7.6 Linux/3.13.0-128-generic Botocore/1.4.93 Resource'}, 'context': {'client_region': u'us-east-1', 'has_streaming_input': False, 'client_config': <botocore.config.Config object at 0x7f849b5faf50>}, 'query_string': '', 'url_path': '/', 'method': u'POST'}
2017-08-23 20:31:03,895 DEBUG [-] Event request-created.sqs.GetQueueUrl: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f849b5faf90>>
2017-08-23 20:31:03,896 DEBUG [-] Calculating signature using v4 auth.
2017-08-23 20:31:03,896 DEBUG [-] CanonicalRequest:
POST
/

host:queue.amazonaws.com
x-amz-date:20170823T203103Z

host;x-amz-date
e2caf6f7b82bbeebb9e57e3fb2a1cf25aeb02b2c3e4739b4f79f0ad2c5ad68ac
2017-08-23 20:31:03,896 DEBUG [-] StringToSign:
AWS4-HMAC-SHA256
20170823T203103Z
20170823/us-east-1/sqs/aws4_request
fff3d0ee7842f0e834162f5ac8ba893fc54c083dfa1ce16e85b841bc257f7138
2017-08-23 20:31:03,896 DEBUG [-] Signature:
ef8cdc2b7c22c013e4f0eaf8c180bf3bd11e88defbb84e0923193d393581ce4c
2017-08-23 20:31:03,897 DEBUG [-] Sending http request: <PreparedRequest [POST]>
2017-08-23 20:31:03,898 INFO [-] Starting new HTTPS connection (1): queue.amazonaws.com
2017-08-23 20:31:08,034 DEBUG [-] 1 active sensor(s)
2017-08-23 20:31:13,035 DEBUG [-] 1 active sensor(s)
2017-08-23 20:31:18,035 DEBUG [-] 1 active sensor(s)
2017-08-23 20:31:23,036 DEBUG [-] 1 active sensor(s)
2017-08-23 20:31:28,036 DEBUG [-] 1 active sensor(s)
2017-08-23 20:31:33,037 DEBUG [-] 1 active sensor(s)
2017-08-23 20:31:38,037 DEBUG [-] 1 active sensor(s)
2017-08-23 20:31:43,038 DEBUG [-] 1 active sensor(s)
2017-08-23 20:31:48,038 DEBUG [-] 1 active sensor(s)
2017-08-23 20:31:53,038 DEBUG [-] 1 active sensor(s)
2017-08-23 20:31:58,039 DEBUG [-] 1 active sensor(s)
2017-08-23 20:32:03,039 DEBUG [-] 1 active sensor(s)
2017-08-23 20:32:03,900 DEBUG [-] ConnectionError received when sending HTTP request.
Traceback (most recent call last):
  File "/opt/stackstorm/virtualenvs/aws/lib/python2.7/site-packages/botocore/endpoint.py", line 207, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/opt/stackstorm/virtualenvs/aws/lib/python2.7/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/opt/stackstorm/virtualenvs/aws/lib/python2.7/site-packages/botocore/vendored/requests/adapters.py", line 419, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPSConnectionPool(host='queue.amazonaws.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPSConnection object at 0x7f849b5db490>, 'Connection to queue.amazonaws.com timed out. (connect timeout=60)'))
2017-08-23 20:32:03,901 DEBUG [-] Event needs-retry.sqs.GetQueueUrl: calling handler <botocore.retryhandler.RetryHandler object at 0x7f849b5fa550>
2017-08-23 20:32:03,901 DEBUG [-] retry needed, retryable exception caught: HTTPSConnectionPool(host='queue.amazonaws.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPSConnection object at 0x7f849b5db490>, 'Connection to queue.amazonaws.com timed out. (connect timeout=60)'))
Traceback (most recent call last):
  File "/opt/stackstorm/virtualenvs/aws/lib/python2.7/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/opt/stackstorm/virtualenvs/aws/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/opt/stackstorm/virtualenvs/aws/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/opt/stackstorm/virtualenvs/aws/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
ConnectTimeout: HTTPSConnectionPool(host='queue.amazonaws.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPSConnection object at 0x7f849b5db490>, 'Connection to queue.amazonaws.com timed out. (connect timeout=60)'))
2017-08-23 20:32:03,902 DEBUG [-] Retry needed, action of: 0.980829229208
2017-08-23 20:32:03,902 DEBUG [-] Response received to retry, sleeping for 0.980829229208 seconds
2017-08-23 20:32:04,883 DEBUG [-] Event request-created.sqs.GetQueueUrl: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f849b5faf90>>
2017-08-23 20:32:04,884 DEBUG [-] Calculating signature using v4 auth.
2017-08-23 20:32:04,884 DEBUG [-] CanonicalRequest:
POST
/

host:queue.amazonaws.com
x-amz-date:20170823T203204Z
```

Could someone please help with the issue.

Thanks in advance.
UM255

**Comment by LindsayHill** [comment]
This line here is probably the relevant part:
```
ConnectTimeout: HTTPSConnectionPool(host='queue.amazonaws.com', port=443)
```

Does your system have outbound TCP/443 access to queue.amazonaws.com? Do you have firewalls or proxies that could affect access?

**Comment by um255** [comment]
Hi Lindsay,

My EC2 instance where i have installed the stackstorm sits behinds a firewall but it has access to the outbound traffic via proxy.

Below is the curl and the nslookup output for queue.amazonaws.com from the ec2 instance

root@# curl -k https://queue.amazonaws.com
UnKnownOperation

root# nslookup queue.amazonaws.com
Server:		XX.XXX.X.XX
Address:	XX.XXX.X.XX#XX

Non-authoritative answer:
Name:	queue.amazonaws.com
Address: XX.XXX.XX.XXX

I have configured the https_proxy and the http_proxy environment variable in the .bashrc profile of the root user.

And also when i run the individual aws actions like ec2_describe_instance from the stackstorm UI, i pass the http_proxy and https_proxy in the env variable of the call and the call succeeds.

Which leads me to believe that the botocore module of the aws pack is not able to use the proxy environment  variables set in the profile of the root user while running the aws sqs sensor.

If you look at the error log, it mentions the below line

2017-08-23 20:32:03,900 DEBUG [-] ConnectionError received when sending HTTP request.
Traceback (most recent call last):
  File "/opt/stackstorm/virtualenvs/aws/lib/python2.7/site-packages/botocore/endpoint.py", line 207, in _get_response
    proxies=self.proxies, timeout=self.timeout)

where i think self.proxies value is getting passed as null and causing the connection error issue.

I still have to look at the core code to figure if the proxy is getting passed to the boto core.

Is there any place where we can configure the proxy environment variable for the sqs sensor or the whole AWS pack itself ??

**Comment by LindsayHill** [comment]
If you're running ST2 >= 2.3.2, you should be able to configure proxy settings in `/etc/default/st2actionrunner` or `/etc/sysconfig/st2actionrunner`, rather than needing to pass it in as an env variable. See https://docs.stackstorm.com/latest/packs.html#ubuntu-16-04-or-rhel-7

That works for actions, but I don't know if it works for sensors. You could try setting those proxy vars in  `/etc/default/st2sensorcontainer`, but I don't know if it will work or not.

**Comment by um255** [comment]
Hi Lindsay,

I configred the actionrunner and st2api under /etc/default and the actions started working without the proxy.

I also configured st2sensorcontainer as you suggested but its still giving the same error as mentioned in the initial issue.

Anything else you think we can try ??

**Comment by LindsayHill** [comment]
I would do these two things:

1/ Edit the sqs_sensor.py code to try injecting proxies there. Good approach would be to read values from pack configuration. Could start with hard-coding for your environment for testing purposes. Then figure out what you need to do with boto3 to pass in a proxy when setting up a new session. Presumably there's some way of doing it. If not, you'll need to set the os environment variables from within sqs_sensor.py, maybe something ugly like 
```python
import os
os.environ["HTTP_PROXY"] = "http://yourproxy.com:1234"
os.environ["HTTPS_PROXY"] = "https://yourproxy1.com:1234"
```

2/ Log an issue against github.com/StackStorm/st2/issues, describing your issue. Include notes on your version, your testing, and that you tried setting values in `/etc/default/st2sensorcontainer`, along with any other relevant information - e.g. logs, notes on if your proxy is doing SSL MiTM, etc.

**Comment by Mierdin** [comment]
@um255 Have you had a chance to try Lindsay's fix? Let us know if there's anything else we can do to help.
